{
 "title": "CampusConnect Microservices - Lab 8 Monitoring Dashboard",
 "tags": [
  "lab8",
  "kubernetes",
  "campusconnect"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Question 1: Are Targets Reachable? (Availability)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"api-gateway\"}",
     "legendFormat": "API Gateway Status"
    }
   ]
  },
  {
   "title": "Question 2: How Much Traffic is Arriving? (Traffic Rate - req/sec)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Question 3: Are Failures Increasing? (Error Rate 4xx / 5xx)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"4..|5..\"}[1m])) by (status, route)",
     "legendFormat": "Status {{status}} ({{route}})"
    }
   ]
  },
  {
   "title": "Question 4: How Long are Requests Taking? (Average Latency - Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[1m])) by (route) / sum(rate(http_request_duration_seconds_count[1m])) by (route)",
     "legendFormat": "{{route}} avg latency"
    }
   ]
  }
 ]
}