apiVersion: v1
kind: ConfigMap
metadata:
  name: campusconnect-config
  namespace: lab8
  labels:
    app.kubernetes.io/name: campusconnect
    app.kubernetes.io/part-of: campusconnect-platform
data:
  PORT: "8080"
  GATEWAY_PORT: "8080"
  USER_SERVICE_PORT: "3001"
  PRODUCT_SERVICE_PORT: "3002"
  ORDER_SERVICE_PORT: "3003"
  USER_SERVICE_URL: "http://user-service:3001"
  PRODUCT_SERVICE_URL: "http://product-service:3002"
  ORDER_SERVICE_URL: "http://order-service:3003"
  NODE_ENV: "production"
