apiVersion: v1
kind: Secret
metadata:
  name: campusconnect-secrets
  namespace: lab8
  labels:
    app.kubernetes.io/name: campusconnect
    app.kubernetes.io/part-of: campusconnect-platform
type: Opaque
# Security Note: Do not commit actual database credentials to GitHub.
stringData:
  # Option A: In-cluster MongoDB service
  MONGO_URI_USER: "mongodb://mongodb:27017/userdb"
  MONGO_URI_PRODUCT: "mongodb://mongodb:27017/productdb"
  MONGO_URI_ORDER: "mongodb://mongodb:27017/orderdb"

  # Option B: MongoDB Atlas (External Managed Database from Lab 7)
  # MONGO_URI_USER: "mongodb+srv://<username>:<password>@<cluster>.mongodb.net/userdb?retryWrites=true&w=majority"
  # MONGO_URI_PRODUCT: "mongodb+srv://<username>:<password>@<cluster>.mongodb.net/productdb?retryWrites=true&w=majority"
  # MONGO_URI_ORDER: "mongodb+srv://<username>:<password>@<cluster>.mongodb.net/orderdb?retryWrites=true&w=majority"
